export const campoRequeridoYup = "Campo Requerido"
export const emailRequeridoYup = "Correo Electronico Invalido"
export const campoSinEspacios = "El Campo no debe comenzar con espacio"
export const telefonoRequeridoYup = "Telefono invalido"
export const celularRequeridoYup = "Celular invalido"
