export * from './ITblTicket'
export * from './ITblDetalleTicket'
export * from './ITblUsuario'
export * from './ITblCategorias'
export * from './ITblEstados'
export * from './ITblRolesUsuario'
export * from './ITblDocumentosTicket'